# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaceName', models.CharField(max_length=64)),
                ('payload', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'interface',
            },
        ),
        migrations.CreateModel(
            name='Interface2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interfaceName', models.CharField(max_length=64)),
                ('payload', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'interface2',
            },
        ),
    ]
